### PR TITLE
Sync/upstream

### PR DESCRIPTION
**Pull request by mustafasalfiti**
Syncing the main upstream branch into this repo main branch

### CODE REVIEW

**Comment by mustafasalfiti** [comment]
@nitin-vavdiya  could you please take a look why the CI fails ?

**Comment by nitin-vavdiya** [comment]
> @nitin-vavdiya could you please take a look why the CI fails ?

Its due to test case, checking

**Comment by nitin-vavdiya** [comment]
failing test cases are fixed.

Now failing due to some other error, 

The same issue is also there in catena-x repo:

https://github.com/eclipse-tractusx/managed-identity-wallet/actions/runs/6482083507/job/17608433269?pr=101

We need to wait till they resolve it or we need to contribute there

**Comment by felipe-zampa** [comment]
Closing this PR due to repository archiving

**Pull request closed without merging**
